const data = [
  {
    id: 1,
    name: 'Rick',
    status: 'Alive',
    species: 'Human',
    image: 'https://rickandmortyapi.com/api/character/avatar/1.jpeg',
    created: '2017-11-04T18:48:46.250Z',
    gender: 'Male',
  },
  {
    id: 2,
    name: 'Morty Smith',
    status: 'Alive',
    species: 'Human',
    image: 'https://rickandmortyapi.com/api/character/avatar/2.jpeg',
    created: '2017-11-04T18:50:21.651Z',
    gender: 'Male',
  },
  {
    id: 3,
    name: 'Summer Smith',
    status: 'Alive',
    species: 'Human',
    image: 'https://rickandmortyapi.com/api/character/avatar/3.jpeg',
    created: '2017-11-04T19:09:56.428Z',
    gender: 'Female',
  },
  {
    id: 4,
    name: 'Beth Smith',
    status: 'Alive',
    species: 'Human',
    image: 'https://rickandmortyapi.com/api/character/avatar/4.jpeg',
    created: '2017-11-04T19:22:43.665Z',
    gender: 'Female',
  },
  {
    id: 5,
    name: 'Jerry Smith',
    status: 'Alive',
    species: 'Human',
    image: 'https://rickandmortyapi.com/api/character/avatar/5.jpeg',
    created: '2017-11-04T19:26:56.301Z',
    gender: 'Male',
  },
  {
    id: 6,
    name: 'Abadango Cluster Princess',
    status: 'Alive',
    species: 'Alien',
    image: 'https://rickandmortyapi.com/api/character/avatar/6.jpeg',
    created: '2017-11-04T19:50:28.250Z',
    gender: 'Female',
  },
  {
    id: 7,
    name: 'Abradolf Lincler',
    status: 'Unknown',
    species: 'Human',
    image: 'https://rickandmortyapi.com/api/character/avatar/7.jpeg',
    created: '2017-11-04T19:59:20.523Z',
    gender: 'Male',
  },
  {
    id: 8,
    name: 'Adjudicator Rick',
    status: 'Dead',
    species: 'Human',
    image: 'https://rickandmortyapi.com/api/character/avatar/8.jpeg',
    created: '2017-11-04T20:03:34.737Z',
    gender: 'Male',
  },
];

export default data;
